
import Wrapper from "@/comps/Wrapper";
import "../globals.css";
import Sidebar from "@/comps/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen ">
          <Sidebar />
          <main className="flex-1">
          <Wrapper><div className="px-4 py-7">{children}</div></Wrapper>
          </main>
        </div>
      </body>
    </html>
  );
}
